import { useState, useEffect } from 'react';
import { useLanguage } from '@/hooks/useLanguage';

export type SupportedLanguage = 'en' | 'nl' | 'fr';

interface LanguageDetectionHook {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Emergency Triage
    'triage.title': 'Emergency Dental Triage',
    'triage.subtitle': 'Please answer the following questions to assess your urgency level',
    'triage.pain.title': 'Pain Level Assessment',
    'triage.pain.question': 'On a scale of 1-10, how severe is your pain?',
    'triage.pain.none': 'No pain (1)',
    'triage.pain.severe': 'Severe pain (10)',
    'triage.symptoms.title': 'Additional Symptoms',
    'triage.symptoms.bleeding': 'Bleeding from gums or teeth',
    'triage.symptoms.swelling': 'Facial or gum swelling',
    'triage.symptoms.fever': 'Fever (>38°C)',
    'triage.symptoms.difficulty': 'Difficulty swallowing or breathing',
    'triage.symptoms.trauma': 'Recent dental trauma or injury',
    'triage.duration.title': 'Duration of Symptoms',
    'triage.duration.question': 'How long have you had these symptoms?',
    'triage.duration.hours': 'Less than 6 hours',
    'triage.duration.day': '6-24 hours',
    'triage.duration.days': '2-7 days',
    'triage.duration.week': 'More than a week',
    'triage.medical.title': 'Medical History',
    'triage.medical.diabetes': 'Diabetes',
    'triage.medical.heart': 'Heart condition',
    'triage.medical.blood': 'Blood disorders',
    'triage.medical.immune': 'Compromised immune system',
    'triage.submit': 'Assess Urgency & Book Appointment',
    'triage.result.emergency': 'EMERGENCY - Immediate attention required',
    'triage.result.high': 'HIGH URGENCY - Same day appointment needed',
    'triage.result.medium': 'MEDIUM URGENCY - Appointment within 2-3 days',
    'triage.result.low': 'LOW URGENCY - Regular appointment needed',
    // Booking
    'booking.title': 'Book Your Appointment',
    'booking.earliest': 'Earliest Available Slots',
    'booking.confirm': 'Confirm Appointment',
    'booking.success': 'Appointment booked successfully!',
    'booking.detailsTitle': 'Appointment Details',
    'booking.dentist': 'Dentist',
    'booking.date': 'Date',
    'booking.time': 'Time',
    'booking.urgency': 'Urgency',
    'booking.urgentArrivalNotice': 'Due to the urgent nature of your case, please arrive 15 minutes early. If your condition worsens, please contact emergency services immediately.',
    'booking.continue': 'Continue to Dashboard',
    'booking.selectDate': 'Select Date',
    'booking.availableTimes': 'Available Times',
    'booking.noSlots': 'No available slots for this date',
    'booking.selectDatePrompt': 'Please select a date to view available times',
    'booking.selectedDentist': 'Selected dentist',
    'booking.selectedBadge': 'Selected',
    // Entry Page (EmergencyTriageEntry)
    'entry.heroTitle': 'Emergency Triage Assessment',
    'entry.heroDesc': 'Fast, secure, and accurate dental emergency assessment',
    'entry.ctaStart': 'Start Emergency Assessment',
    'entry.steps.assessSymptoms.title': 'Assess Symptoms',
    'entry.steps.assessSymptoms.desc': 'Answer questions about your pain and symptoms',
    'entry.steps.getUrgency.title': 'Get Urgency Level',
    'entry.steps.getUrgency.desc': 'Receive your urgency rating (1-5 scale)',
    'entry.steps.viewSlots.title': 'View Available Slots',
    'entry.steps.viewSlots.desc': 'See prioritized appointment times',
    'entry.steps.bookInstantly.title': 'Book Instantly',
    'entry.steps.bookInstantly.desc': 'Confirm your appointment immediately',
    'entry.emergencyNotice.title': 'Life-Threatening Emergency?',
    'entry.emergencyNotice.desc': "If you're experiencing severe breathing difficulties, uncontrolled bleeding, or signs of serious infection, call emergency services (112) immediately.",
    'entry.gdpr.title': 'Privacy & Security',
    'entry.gdpr.desc': 'Your health information is protected under GDPR. Data is encrypted and only shared with your selected dentist for appointment purposes.',
    'entry.return': 'Return to Main App',
    'entry.stats.minutes': '2-3 Minutes',
    'entry.stats.quick': 'Quick Assessment',
    'entry.stats.gdpr': 'GDPR Compliant',
    'entry.stats.secure': 'Secure & Private',
    'entry.stats.directBooking': 'Direct Booking',
    'entry.stats.noChat': 'No Chat Required',
    // Common
    'common.cancel': 'Cancel',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.success': 'Success',
  },
  nl: {
    // Emergency Triage
    'triage.title': 'Spoed Tandheelkundige Triage',
    'triage.subtitle': 'Beantwoord de volgende vragen om uw urgentieniveau te beoordelen',
    'triage.pain.title': 'Pijnbeoordeling',
    'triage.pain.question': 'Op een schaal van 1-10, hoe erg is uw pijn?',
    'triage.pain.none': 'Geen pijn (1)',
    'triage.pain.severe': 'Erge pijn (10)',
    'triage.symptoms.title': 'Aanvullende Symptomen',
    'triage.symptoms.bleeding': 'Bloeding uit tandvlees of tanden',
    'triage.symptoms.swelling': 'Zwelling van gezicht of tandvlees',
    'triage.symptoms.fever': 'Koorts (>38°C)',
    'triage.symptoms.difficulty': 'Moeite met slikken of ademen',
    'triage.symptoms.trauma': 'Recent tandheelkundig trauma of verwonding',
    'triage.duration.title': 'Duur van Symptomen',
    'triage.duration.question': 'Hoe lang heeft u deze symptomen al?',
    'triage.duration.hours': 'Minder dan 6 uur',
    'triage.duration.day': '6-24 uur',
    'triage.duration.days': '2-7 dagen',
    'triage.duration.week': 'Meer dan een week',
    'triage.medical.title': 'Medische Geschiedenis',
    'triage.medical.diabetes': 'Diabetes',
    'triage.medical.heart': 'Hartaandoening',
    'triage.medical.blood': 'Bloedziekten',
    'triage.medical.immune': 'Verzwakt immuunsysteem',
    'triage.submit': 'Urgentie Beoordelen & Afspraak Maken',
    'triage.result.emergency': 'SPOED - Onmiddellijke aandacht vereist',
    'triage.result.high': 'HOGE URGENTIE - Afspraak dezelfde dag nodig',
    'triage.result.medium': 'GEMIDDELDE URGENTIE - Afspraak binnen 2-3 dagen',
    'triage.result.low': 'LAGE URGENTIE - Reguliere afspraak nodig',
    // Booking
    'booking.title': 'Uw Afspraak Inplannen',
    'booking.earliest': 'Vroegst Beschikbare Tijdsloten',
    'booking.confirm': 'Afspraak Bevestigen',
    'booking.success': 'Afspraak succesvol geboekt!',
    'booking.detailsTitle': 'Afsprakengegevens',
    'booking.dentist': 'Tandarts',
    'booking.date': 'Datum',
    'booking.time': 'Tijd',
    'booking.urgency': 'Urgentie',
    'booking.urgentArrivalNotice': 'Vanwege de urgentie van uw situatie vragen we u 15 minuten eerder te komen. Als uw toestand verslechtert, neem dan onmiddellijk contact op met de hulpdiensten.',
    'booking.continue': 'Doorgaan naar Dashboard',
    'booking.selectDate': 'Selecteer Datum',
    'booking.availableTimes': 'Beschikbare Tijden',
    'booking.noSlots': 'Geen beschikbare tijden voor deze datum',
    'booking.selectDatePrompt': 'Selecteer een datum om beschikbare tijden te zien',
    'booking.selectedDentist': 'Geselecteerde tandarts',
    'booking.selectedBadge': 'Geselecteerd',
    // Entry Page (EmergencyTriageEntry)
    'entry.heroTitle': 'Spoed Triage Beoordeling',
    'entry.heroDesc': 'Snelle, veilige en nauwkeurige tandheelkundige spoedbeoordeling',
    'entry.ctaStart': 'Start Spoedbeoordeling',
    'entry.steps.assessSymptoms.title': 'Beoordeel Symptomen',
    'entry.steps.assessSymptoms.desc': 'Beantwoord vragen over uw pijn en symptomen',
    'entry.steps.getUrgency.title': 'Ontvang Urgentieniveau',
    'entry.steps.getUrgency.desc': 'Ontvang uw urgentiescore (schaal 1-5)',
    'entry.steps.viewSlots.title': 'Bekijk Beschikbare Tijden',
    'entry.steps.viewSlots.desc': 'Zie geprioriteerde afspraakmomenten',
    'entry.steps.bookInstantly.title': 'Boek Direct',
    'entry.steps.bookInstantly.desc': 'Bevestig uw afspraak onmiddellijk',
    'entry.emergencyNotice.title': 'Levensbedreigende Noodsituatie?',
    'entry.emergencyNotice.desc': 'Als u ernstige ademhalingsproblemen, oncontroleerbare bloedingen of tekenen van een ernstige infectie ervaart, bel dan onmiddellijk de hulpdiensten (112).',
    'entry.gdpr.title': 'Privacy & Beveiliging',
    'entry.gdpr.desc': 'Uw gezondheidsgegevens worden beschermd volgens de AVG. Gegevens worden versleuteld en alleen gedeeld met uw geselecteerde tandarts voor afspraakdoeleinden.',
    'entry.return': 'Terug naar de Hoofdapp',
    'entry.stats.minutes': '2-3 Minuten',
    'entry.stats.quick': 'Snelle beoordeling',
    'entry.stats.gdpr': 'AVG-conform',
    'entry.stats.secure': 'Veilig & Privé',
    'entry.stats.directBooking': 'Direct boeken',
    'entry.stats.noChat': 'Geen chat vereist',
    // Common
    'common.cancel': 'Annuleren',
    'common.next': 'Volgende',
    'common.back': 'Terug',
    'common.loading': 'Laden...',
    'common.success': 'Succes',
  },
  fr: {
    // Emergency Triage
    'triage.title': 'Triage Dentaire d\'Urgence',
    'triage.subtitle': 'Veuillez répondre aux questions suivantes pour évaluer votre niveau d\'urgence',
    'triage.pain.title': 'Évaluation de la Douleur',
    'triage.pain.question': 'Sur une échelle de 1-10, quelle est l\'intensité de votre douleur?',
    'triage.pain.none': 'Aucune douleur (1)',
    'triage.pain.severe': 'Douleur sévère (10)',
    'triage.symptoms.title': 'Symptômes Supplémentaires',
    'triage.symptoms.bleeding': 'Saignement des gencives ou des dents',
    'triage.symptoms.swelling': 'Gonflement du visage ou des gencives',
    'triage.symptoms.fever': 'Fièvre (>38°C)',
    'triage.symptoms.difficulty': 'Difficulté à avaler ou respirer',
    'triage.symptoms.trauma': 'Traumatisme dentaire récent ou blessure',
    'triage.duration.title': 'Durée des Symptômes',
    'triage.duration.question': 'Depuis combien de temps avez-vous ces symptômes?',
    'triage.duration.hours': 'Moins de 6 heures',
    'triage.duration.day': '6-24 heures',
    'triage.duration.days': '2-7 jours',
    'triage.duration.week': 'Plus d\'une semaine',
    'triage.medical.title': 'Antécédents Médicaux',
    'triage.medical.diabetes': 'Diabète',
    'triage.medical.heart': 'Maladie cardiaque',
    'triage.medical.blood': 'Troubles sanguins',
    'triage.medical.immune': 'Système immunitaire compromis',
    'triage.submit': 'Évaluer l\'Urgence et Prendre Rendez-vous',
    'triage.result.emergency': 'URGENCE - Attention immédiate requise',
    'triage.result.high': 'URGENCE ÉLEVÉE - Rendez-vous le jour même nécessaire',
    'triage.result.medium': 'URGENCE MOYENNE - Rendez-vous dans 2-3 jours',
    'triage.result.low': 'URGENCE FAIBLE - Rendez-vous régulier nécessaire',
    // Booking
    'booking.title': 'Réserver Votre Rendez-vous',
    'booking.earliest': 'Créneaux Disponibles au Plus Tôt',
    'booking.confirm': 'Confirmer le Rendez-vous',
    'booking.success': 'Rendez-vous réservé avec succès!',
    'booking.detailsTitle': 'Détails du rendez-vous',
    'booking.dentist': 'Dentiste',
    'booking.date': 'Date',
    'booking.time': 'Heure',
    'booking.urgency': 'Urgence',
    'booking.urgentArrivalNotice': 'En raison du caractère urgent de votre cas, veuillez arriver 15 minutes en avance. Si votre état s’aggrave, contactez immédiatement les services d’urgence.',
    'booking.continue': 'Continuer vers le tableau de bord',
    'booking.selectDate': 'Sélectionner une date',
    'booking.availableTimes': 'Horaires disponibles',
    'booking.noSlots': 'Aucun créneau disponible pour cette date',
    'booking.selectDatePrompt': 'Veuillez sélectionner une date pour voir les horaires disponibles',
    'booking.selectedDentist': 'Dentiste sélectionné',
    'booking.selectedBadge': 'Sélectionné',
    // Entry Page (EmergencyTriageEntry)
    'entry.heroTitle': "Évaluation de Triage d'Urgence",
    'entry.heroDesc': 'Évaluation dentaire d’urgence rapide, sécurisée et précise',
    'entry.ctaStart': "Commencer l'évaluation d'urgence",
    'entry.steps.assessSymptoms.title': 'Évaluer les symptômes',
    'entry.steps.assessSymptoms.desc': 'Répondez aux questions sur votre douleur et vos symptômes',
    'entry.steps.getUrgency.title': "Obtenir le niveau d'urgence",
    'entry.steps.getUrgency.desc': 'Recevez votre niveau d’urgence (échelle 1-5)',
    'entry.steps.viewSlots.title': 'Voir les créneaux disponibles',
    'entry.steps.viewSlots.desc': 'Consultez les horaires de rendez-vous prioritaires',
    'entry.steps.bookInstantly.title': 'Réserver instantanément',
    'entry.steps.bookInstantly.desc': 'Confirmez votre rendez-vous immédiatement',
    'entry.emergencyNotice.title': 'Urgence vitale ?',
    'entry.emergencyNotice.desc': "Si vous avez de graves difficultés respiratoires, des saignements incontrôlables ou des signes d’infection grave, appelez immédiatement les services d’urgence (112).",
    'entry.gdpr.title': 'Confidentialité & Sécurité',
    'entry.gdpr.desc': 'Vos informations de santé sont protégées selon le RGPD. Les données sont chiffrées et uniquement partagées avec le dentiste sélectionné pour la prise de rendez-vous.',
    'entry.return': "Retour à l'application principale",
    'entry.stats.minutes': '2-3 minutes',
    'entry.stats.quick': 'Évaluation rapide',
    'entry.stats.gdpr': 'Conforme RGPD',
    'entry.stats.secure': 'Sécurisé & Privé',
    'entry.stats.directBooking': 'Réservation directe',
    'entry.stats.noChat': 'Sans chat requis',
    // Common
    'common.cancel': 'Annuler',
    'common.next': 'Suivant',
    'common.back': 'Retour',
    'common.loading': 'Chargement...',
    'common.success': 'Succès',
  },
};

export const useLanguageDetection = (): LanguageDetectionHook => {
  const { language: contextLanguage, setLanguage: setContextLanguage } = useLanguage();

  const t = (key: string): string => {
    return translations[contextLanguage as SupportedLanguage]?.[key] || key;
  };

  return {
    language: contextLanguage as SupportedLanguage,
    setLanguage: setContextLanguage as (lang: SupportedLanguage) => void,
    t,
  };
};