import '@testing-library/jest-dom';
// Mock Supabase client channel for tests
jest.mock('@/integrations/supabase/client', () => {
  const actual = jest.requireActual('@/integrations/supabase/client');
  const supabase = {
    ...actual.supabase,
    channel: jest.fn().mockReturnValue({
      on: jest.fn().mockReturnThis(),
      subscribe: jest.fn().mockReturnValue({ unsubscribe: jest.fn() }),
      unsubscribe: jest.fn(),
    }),
  };
  return { ...actual, supabase };
});

// Mock IntersectionObserver (with full shape)
Object.defineProperty(global, 'IntersectionObserver', {
  writable: true,
  value: class IntersectionObserver {
    readonly root: Element | null = null;
    readonly rootMargin: string = '';
    readonly thresholds: ReadonlyArray<number> = [0];
    constructor(_callback?: any, _options?: any) { }
    observe(): void { }
    unobserve(): void { }
    disconnect(): void { }
    takeRecords(): IntersectionObserverEntry[] { return []; }
  },
});

// Mock ResizeObserver
global.ResizeObserver = class ResizeObserver {
  constructor() { }
  disconnect() { }
  observe() { }
  unobserve() { }
};

// Mock matchMedia
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});

// Mock window.scrollTo
Object.defineProperty(window, 'scrollTo', {
  writable: true,
  value: jest.fn(),
});

// Provide a default LanguageContext to avoid errors in tests rendering components
jest.mock('@/hooks/useLanguage', () => {
  const actual = jest.requireActual('@/hooks/useLanguage');
  return {
    ...actual,
    useLanguage: () => ({
      language: 'en',
      setLanguage: jest.fn(),
      currentLanguage: 'en',
      changeLanguage: jest.fn(),
      t: {
        error: 'Error',
        success: 'Success',
        microphoneAccessError: '',
        transcriptionFailed: '',
        voiceProcessingError: '',
        settings: 'Settings',
        general: 'General',
        theme: 'Theme',
        personal: 'Personal',
        language: 'Language',
        light: 'Light',
        dark: 'Dark',
        save: 'Save',
        confirm: 'Confirm',
        cancel: 'Cancel',
        close: 'Close',
        retry: 'Retry',
        firstName: 'First Name',
        lastName: 'Last Name',
        phoneNumber: 'Phone Number',
        dateOfBirth: 'Date of Birth',
        medicalHistory: 'Medical History',
        personalInformation: 'Personal Information',
        savePersonalInfo: 'Save Personal Information',
        address: 'Address',
        emergencyContact: 'Emergency Contact',
        enterAddress: 'Enter your address',
        enterEmergencyContact: 'Enter emergency contact information',
        languageUpdated: 'Language Updated',
        languageChangedTo: 'Language changed to',
        themeUpdated: 'Theme Updated',
        switchedToMode: 'Switched to',
        personalInfoSaved: 'Personal Information Saved',
        personalInfoUpdated: 'Your information has been updated successfully.',
        informationConfirmed: 'Information Confirmed',
        changesSaved: 'Changes Saved',
        privacyNotice: 'Privacy notice',
        signOut: 'Sign Out',
        signIn: 'Sign In',
        signUp: 'Sign Up',
        createAccount: 'Create Account',
        email: 'Email',
        password: 'Password',
        phone: 'Phone',
        optional: 'optional',
        welcome: 'Welcome',
        accessDentiBot: 'Access Caberu',
        signInOrCreate: 'Sign in or create an account',
        signInButton: 'Sign in',
        createAccountButton: 'Create account',
        accountCreatedSuccess: 'Account created successfully!',
        checkEmailConfirm: 'Check your email to confirm your account.',
        signUpError: 'Sign up error',
        signInError: 'Sign in error',
        signInSuccess: 'Sign in successful!',
        welcomeToDentiBot: 'Welcome to Caberu.',
        enterFirstName: '',
        enterLastName: '',
        enterPhoneNumber: '',
        enterMedicalHistory: '',
        selectLanguage: '',
        enterEmail: '',
        enterPassword: '',
        dentalAssistant: 'Dental Assistant',
        typeMessage: 'Type your message...',
        send: 'Send',
        welcomeMessage: 'Hello!',
        detailedWelcomeMessage: 'Welcome',
        detailedWelcomeMessageWithName: (name: string) => `Welcome ${name}`,
        intelligentDentalAssistant: 'Your Intelligent Dental Assistant 24/7',
        experienceFuture: '',
        viewOurDentists: 'View Our Dentists',
        aiDiagnosis: 'AI Diagnosis',
        aiDiagnosisDesc: '',
        smartBooking: 'Smart Booking',
        smartBookingDesc: '',
        support24_7: '24/7 Support',
        support24_7Desc: '',
        initializingExperience: '',
        preparingAssistant: '',
        chat: 'Chat',
        appointments: 'Appointments',
        bookAppointment: 'Book Appointment',
        bookConsultationDescription: '',
        chooseDentist: 'Choose Dentist',
        selectDate: 'Select Date',
        selectTime: 'Select Time',
        availableSlots: 'Available Slots',
        consultationReason: 'Consultation Reason',
        generalConsultation: 'General consultation',
        routineCheckup: 'Routine checkup',
        dentalPain: 'Dental pain',
        emergency: 'Emergency',
        cleaning: 'Cleaning',
        other: 'Other',
        bookNow: 'Book Now',
        appointmentConfirmed: 'Appointment confirmed!',
        errorTitle: 'Error',
        cannotLoadSlots: 'Unable to load available slots',
        cannotLoadDentists: 'Unable to load dentist list',
        missingInformation: 'Missing information',
        selectDentistDateTime: 'Please select a dentist, date and time',
        slotNoLongerAvailable: 'This slot is no longer available',
        cannotCreateAppointment: 'Unable to create appointment',
        myAppointments: 'My Appointments',
        appointmentHistory: 'Appointment History',
        upcomingAppointments: 'Upcoming Appointments',
        pastAppointments: 'Past Appointments',
        newAppointment: 'New',
        appointmentDetails: 'Appointment Details',
        loading: 'Loading...',
        noUpcomingAppointments: 'No upcoming appointments',
        noPastAppointments: 'No past appointments',
        reschedule: 'Reschedule',
        cancelAppointment: 'Cancel',
        confirmCancellation: 'Cancel Appointment',
        confirmCancellationMessage: 'Are you sure?',
        keepAppointment: 'Keep Appointment',
        yesCancelAppointment: 'Yes, Cancel',
        appointmentCancelled: 'Appointment cancelled successfully',
        failedToCancelAppointment: 'Failed to cancel appointment',
        showMyAppointments: 'Here are your appointments:',
        nextAppointment: 'Your next appointment is:',
        suggestedTime: (dentist: string, time: string) => `${time} with ${dentist}`,
        wouldYouLikeToBook: 'Would you like to book this appointment?',
        seeOtherOptions: 'See other options',
        appointmentSuggestion: (dentist: string, date: string, time: string) => `${date} ${time} ${dentist}`,
        bookThisSlot: 'Book this slot',
        showOtherTimes: 'Show other times',
        settingsUpdated: 'Settings Updated',
        preferencesChanged: 'Your preferences have been updated',
        microphoneError: 'Microphone Error',
        cameraError: 'Camera Error',
        mediaAccessDenied: 'Media access was denied',
        mediaNotSupported: 'Media features are not supported',
        tryAgain: 'Try Again',
        privacyPolicyLink: 'Privacy Policy',
        dataHandlingInfo: 'Data handling info',
        invalidPhoneFormat: 'Please enter a valid phone number',
        invalidEmailFormat: 'Please enter a valid email address',
        requiredField: 'This field is required',
        consentHealthData: '',
        childConsentNote: '',
        downloadMyData: 'Download My Data',
        deleteAccount: 'Delete My Account & Data',
        deleteAccountConfirm: 'Are you sure?',
        aiAdviceDisclaimer: 'AI suggestions disclaimer',
        welcomeToFirstSmile: 'Welcome to First Smile AI! 🦷',
        yourAIDentalAssistant: 'Your AI Dental Assistant',
        onboardingIntro: '',
        smartFeaturesService: '',
        aiChat: 'AI Chat',
        aiChatDesc: '',
        photoAnalysis: 'Photo Analysis',
        photoAnalysisDesc: '',
        familyCare: 'Family Care',
        familyCareDesc: '',
        bookForFamilyTitle: 'Book for Anyone in Your Family',
        familyFriendlyBooking: 'Family-Friendly Booking',
        bookForYourself: 'Book appointments for yourself',
        bookForChildren: 'Book for your children',
        bookForFamily: 'Book for family members',
        alwaysTellDuration: 'I\'ll always tell you appointment duration and end time',
        readyToStart: 'Ready to Get Started?',
        youreAllSet: "You're All Set! 🎉",
        onboardingEnd: 'Start chatting with me below...',
        proTip: 'Pro Tip',
        proTipText: 'Just tell me what\'s bothering you',
        letsStart: "Let's Start!",
        next: 'Next',
        back: 'Back',
        previewNotice: 'This is a working preview',
        aiDisclaimer: 'This assistant uses AI.',
        acceptTerms: 'I accept the Terms and Conditions',
        viewTerms: 'View Terms',
        termsTitle: 'Terms and Conditions',
        termsIntro: 'Please read these terms carefully',
        termsUse: 'Use responsibly',
        termsPrivacy: 'We handle your data...',
        termsMedical: 'Always consult a professional',
        selectPreferredLanguage: 'Select Your Preferred Language',
        languageSelectionDescription: 'Choose your language',
        'triage.title': 'Emergency Dental Triage',
      },
    }),
  };
});