// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Prefer environment variables; fall back to generated defaults for local dev
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://gjvxcisbaxhhblhsytar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqdnhjaXNiYXhoaGJsaHN5dGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjU4MDUsImV4cCI6MjA2NzY0MTgwNX0.p4HO2McB5IqP9iQ_p_Z6yHKCkKyDXuIm7ono6UJZcmM";

// Warn in development if using fallback credentials
if (import.meta.env.DEV && (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY)) {
  console.warn('⚠️  Using default Supabase credentials. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env for production.');
}

export { SUPABASE_URL };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Faster auth by using PKCE
    flowType: 'pkce',
  },
  // Performance optimizations
  global: {
    headers: {
      // Enable compression for faster responses
      'Accept-Encoding': 'gzip, deflate, br',
    },
  },
  // Realtime configuration
  realtime: {
    // Reduce heartbeat for better battery/performance
    params: {
      eventsPerSecond: 10,
    },
  },
  // Database connection pooling
  db: {
    schema: 'public',
  },
});

export const getFunctionUrl = (name: string) => `${SUPABASE_URL}/functions/v1/${name}`;

// Helper to abort slow requests
export const createAbortableQuery = (timeoutMs = 10000) => {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  return {
    signal: controller.signal,
    cleanup: () => clearTimeout(timeoutId),
  };
};