name: Deploy Supabase Edge Functions

on:
  workflow_dispatch:
  push:
    paths:
      - "supabase/functions/**"
      - "supabase/config.toml"

env:
  SUPABASE_PROJECT_REF: gjvxcisbaxhhblhsytar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Configure auth and optional secrets
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ env.SUPABASE_PROJECT_REF }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "Missing SUPABASE_ACCESS_TOKEN GitHub secret" >&2
            exit 1
          fi
          export SUPABASE_ACCESS_TOKEN="$SUPABASE_ACCESS_TOKEN"
          if [ -n "$SUPABASE_SERVICE_ROLE_KEY" ]; then
            supabase secrets set SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY" \
              --project-ref "$SUPABASE_PROJECT_REF"
          else
            echo "SUPABASE_SERVICE_ROLE_KEY not provided; skipping secrets set"
          fi

      - name: Deploy claim-profile function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ env.SUPABASE_PROJECT_REF }}
        run: |
          supabase functions deploy claim-profile --project-ref "$SUPABASE_PROJECT_REF"

      - name: Deploy dev-claim-bypass function (optional)
        if: ${{ env.SUPABASE_PROJECT_REF != '' }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ env.SUPABASE_PROJECT_REF }}
        run: |
          supabase functions deploy dev-claim-bypass --project-ref "$SUPABASE_PROJECT_REF" || echo "Skipping dev-claim-bypass"

      - name: Verify claim-profile endpoint
        env:
          SUPABASE_PROJECT_REF: ${{ env.SUPABASE_PROJECT_REF }}
        run: |
          curl -sS -i -X POST "https://${SUPABASE_PROJECT_REF}.supabase.co/functions/v1/claim-profile" \
            -H "Content-Type: application/json" \
            --data '{"email":"test@example.com"}' | sed -n '1,20p'